// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokAsset, StoryblokMultilink } from '../storyblok.d.ts';
export interface BlockBento {
  headline?: string;
  headline_a11y?: boolean;
  text?: StoryblokRichtext;
  about?: StoryblokRichtext;
  testimonials?: Testimonial[];
  background: number | string;
  component: "block_bento";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockFaq {
  headline?: string;
  faq?: Faq[];
  background: number | string;
  component: "block_faq";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockHero {
  signal?: boolean;
  headline?: string;
  text?: StoryblokRichtext;
  cta?: string;
  media?: StoryblokAsset;
  footnote?: StoryblokRichtext;
  background: number | string;
  component: "block_hero";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockPlay {
  headline?: string;
  headline_a11y?: boolean;
  text?: StoryblokRichtext;
  background: number | string;
  component: "block_play";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockProjects {
  headline?: string;
  headline_a11y?: boolean;
  text?: StoryblokRichtext;
  projects?: Project[];
  background: number | string;
  component: "block_projects";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockText {
  headline?: string;
  text?: StoryblokRichtext;
  background: number | string;
  component: "block_text";
  _uid: string;
  _editable?: string | undefined;
}

export interface Faq {
  question?: string;
  answer?: StoryblokRichtext;
  component: "faq";
  _uid: string;
  _editable?: string | undefined;
}

export interface Page {
  blocks?: (
    BlockBento | BlockFaq | BlockHero | BlockPlay | BlockProjects | BlockText | Faq | Page | Project | Testimonial
  )[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface Project {
  headline?: string;
  text?: StoryblokRichtext;
  media?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "project";
  _uid: string;
  _editable?: string | undefined;
}

export interface Testimonial {
  quote: StoryblokRichtext;
  name?: string;
  subtext?: string;
  component: "testimonial";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = Page;
